version: "3.8"

services:
  #  edirotmtzbackend:
  #    image: edirotmtzbackend
  #    build:
  #      context: .
  #      dockerfile: Dockerfile

  dev_db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    ports:
      - '5432:5432'
    
    volumes:
      - dev_db:/var/lib/postgresql/data

volumes:
  dev_db:
    driver: local